AppSaresp_2024/Models/Aluno.cs
using System.ComponentModel.DataAnnotations;

namespace AppSaresp_2024.Models
{
    public class Aluno
    {
        [Display(Name = "Código")]
        public int? IdAluno { get; set; }

        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "O campo nome é obrigatório")]
        public string nome { get; set; }

        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "O campo Telefone é obrigatório")]
        public Decimal telefone { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "O campo email é obrigatório")]
        public string email { get; set; }

        [Display(Name = "Turma")]
        [Required(ErrorMessage = "O campo Turma é obrigatório")]
        public string turma { get; set; }

        [Display(Name = "Sala")]
        [Required(ErrorMessage = "O campo Sala é obrigatório")]
        public string serie { get; set; }

        [Display(Name = "Nascimento")]
        [Required(ErrorMessage = "O campo nascimento é obrigatório")]
        [DataType(DataType.DateTime)]
        public DateTime data_nasc { get; set; }
    }
}

AppSaresp_2024/Models/ErrorViewModel.cs
namespace AppSaresp_2024.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppSaresp_2024/Models/Professor.cs
using System.ComponentModel.DataAnnotations;

namespace AppSaresp_2024.Models
{
    public class Professor
    {
        [Display(Name = "Código")]
        public int? IdProfessor { get; set; }

        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "O campo nome é obrigatório")]
        public string nome { get; set; }

        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "O campo Telefone é obrigatório")]
        public Decimal telefone { get; set; }

        [Display(Name = "CPF")]
        [Required(ErrorMessage = "O campo CPF é obrigatório")]
        public Decimal cpf { get; set; }

        [Display(Name = "RG")]
        [Required(ErrorMessage = "O campo RG é obrigatório")]
        public string rg { get; set; }

        [Display(Name = "Nascimento")]
        [Required(ErrorMessage = "O campo nascimento é obrigatório")]
        [DataType(DataType.DateTime)]
        public DateTime data_nasc { get; set; }
    }
}

AppSaresp_2024/Controllers/AlunoController.cs
using AppSaresp_2024.Models;
using AppSaresp_2024.Repository;
using AppSaresp_2024.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppSaresp_2024.Controllers
{

    public class AlunoController : Controller
    {
        private IAlunoRepository _alunoRepository;
        public AlunoController(IAlunoRepository alunoRepository)
        {
            _alunoRepository = alunoRepository;
        }

        public IActionResult Index()
        {
            return View(_alunoRepository.ObterTodosAlunos());
        }
        [HttpGet]
        public IActionResult CadastrarAluno()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CadastrarAluno(Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                _alunoRepository.Cadastrar(aluno);
            }
            return View();
        }
        [HttpGet]
        public IActionResult AtualizarAluno(int id)
        {
            return View(_alunoRepository.ObterAluno(id));
        }
        [HttpPost]
        public IActionResult AtualizarAluno(Aluno aluno)
        {
            _alunoRepository.Atualizar(aluno);

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult DetalhesAluno(int id)
        {
            return View(_alunoRepository.ObterAluno(id));
        }
        [HttpPost]
        public IActionResult DetalhesAluno(Aluno aluno)
        {
            _alunoRepository.Atualizar(aluno);

            return RedirectToAction(nameof(Index));
        }
        public IActionResult ExcluirAluno(int id)
        {
            _alunoRepository.Excluir(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AppSaresp_2024/Controllers/HomeController.cs
using AppSaresp_2024.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppSaresp_2024.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppSaresp_2024/Controllers/ProfessorController.cs
using AppSaresp_2024.Models;
using AppSaresp_2024.Repository;
using AppSaresp_2024.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppSaresp_2024.Controllers
{

    public class ProfessorController : Controller
    {
        private IProfessorRepository _professorRepository;
        public ProfessorController(IProfessorRepository professorRepository)
        {
            _professorRepository = professorRepository;
        }

        public IActionResult Index()
        {
            return View(_professorRepository.ObterTodosProfessores());
        }
        [HttpGet]
        public IActionResult CadastrarProfessor()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CadastrarProfessor(Professor professor)
        {
            if (ModelState.IsValid)
            {
                _professorRepository.Cadastrar(professor);
            }
            return View();
        }
        [HttpGet]
        public IActionResult AtualizarProfessor(int id)
        {
            return View(_professorRepository.ObterProfessor(id));
        }
        [HttpPost]
        public IActionResult AtualizarProfessor(Professor professor)
        {
            _professorRepository.Atualizar(professor);

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult DetalhesProfessor(int id)
        {
            return View(_professorRepository.ObterProfessor(id));
        }
        [HttpPost]
        public IActionResult DetalhesProfessor(Professor professor)
        {
            _professorRepository.Atualizar(professor);

            return RedirectToAction(nameof(Index));
        }
        public IActionResult ExcluirProfessor(int id)
        {
            _professorRepository.Excluir(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AppSaresp_2024/Views/Aluno/AtualizarAluno.cshtml
@model AppSaresp_2024.Models.Aluno

@{
    ViewData["Title"] = "AtualizarAluno";
}

<h4>Editar o Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarAluno">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdAluno" class="form-control" />

            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="serie" class="control-label"></label>
                <input asp-for="serie" class="form-control" />
                <span asp-validation-for="serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="turma" class="control-label"></label>
                <input asp-for="turma" class="form-control" />
                <span asp-validation-for="turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="data_nasc" class="control-label"></label>
                <input type="date" asp-for="data_nasc" class="form-control" />
                <span asp-validation-for="data_nasc" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AppSaresp_2024/Views/Aluno/CadastrarAluno.cshtml
@model AppSaresp_2024.Models.Aluno

@{
    ViewData["Title"] = "CadastrarAluno";
}

<h1>Área de Cadastro</h1>

<h4>Cadastrar Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarAluno">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="serie" class="control-label"></label>
                <input asp-for="serie" class="form-control" />
                <span asp-validation-for="serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="turma" class="control-label"></label>
                <input asp-for="turma" class="form-control" />
                <span asp-validation-for="turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="data_nasc" class="control-label"></label>
                <input type="date" asp-for="data_nasc" class="form-control" />
                <span asp-validation-for="data_nasc" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" onclick="alert('Aluno cadstrado com sucesso')"/>
                <a class="btn btn-secondary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AppSaresp_2024/Views/Aluno/DetalhesAluno.cshtml
@model AppSaresp_2024.Models.Aluno

@{
    ViewData["Title"] = "DetalhesAluno";
}

<h1>Detalhes do Aluno</h1>
<br />
<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.IdAluno) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.IdAluno)  </dd>

        <dt class="col-sm-2">  @Html.DisplayNameFor(model => model.nome)  </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.nome) </dd>

        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.email) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.email)</dd>

        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.turma) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.turma)</dd>

        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.serie) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.serie)</dd>

        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.telefone) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.telefone)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.data_nasc)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.data_nasc) </dd>
    </dl>
</div>
<br />
<div>
    @* <button type="button" class="btn btn-warning">
    @Html.ActionLink("Editar", "AtualizarAluno", new { id = Model.IdAluno })
    </button> *@
    <a class="btn btn-primary" asp-action="AtualizarAluno">Editar</a>
    <a class="btn btn-secondary" asp-action="Index">Voltar</a>
    @* <button type="button" class="btn btn-secondary">
    @Html.ActionLink("Voltar", "Index")
    </button> *@
</div>

AppSaresp_2024/Views/Aluno/Index.cshtml
@model IEnumerable<AppSaresp_2024.Models.Aluno>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Alunos</h1>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col"> @Html.DisplayNameFor(model => model.IdAluno) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.nome) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.email)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.turma)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.serie)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.telefone)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.data_nasc) </th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Aluno aluno in Model)
            {
                <tr>
                    <td>@aluno.IdAluno</td>
                    <td>@aluno.nome</td>
                    <td>@aluno.email</td>
                    <td>@aluno.turma</td>
                    <td>@aluno.serie</td>
                    <td>@aluno.telefone</td>
                    <td>@aluno.data_nasc.ToString("dd/MM/yyyy")</td>
                    <td>
                        <button type="button" class="btn btn-warning botaoatualiza">
                            @Html.ActionLink("Editar", "AtualizarAluno", new { id = aluno.IdAluno })
                        </button>

                        <button type="button" class="btn btn-secondary botaodetalhes">
                            @Html.ActionLink("Detalhes", "DetalhesAluno", new { id = aluno.IdAluno })
                        </button>

                        <button type="button" class="btn btn-danger botaoexcluir">
                            @Html.ActionLink("Excluir", "ExcluirAluno", new { id = aluno.IdAluno },
                                     new { onclick = "return confirm('Deseja realmente desativar?');" })
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<p><a class="btn btn-primary" asp-action="CadastrarAluno" asp-controller="Aluno">Cadastrar</a></p>

AppSaresp_2024/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppSaresp_2024/Views/Professor/AtualizarProfessor.cshtml
@model AppSaresp_2024.Models.Professor

@{
    ViewData["Title"] = "AtualizarProfessor";
}

<h4>Editar o Professor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarProfessor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdProfessor" class="form-control" />

            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cpf" class="control-label"></label>
                <input asp-for="cpf" class="form-control" />
                <span asp-validation-for="cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rg" class="control-label"></label>
                <input asp-for="rg" class="form-control" />
                <span asp-validation-for="rg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="data_nasc" class="control-label"></label>
                <input type="date" asp-for="data_nasc" class="form-control" />
                <span asp-validation-for="data_nasc" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AppSaresp_2024/Views/Professor/CadastrarProfessor.cshtml
@model AppSaresp_2024.Models.Professor

@{
    ViewData["Title"] = "CadastrarProfessor";
}

<h1>Área de Cadastro</h1>

<h4>Cadastrar Professor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarProfessor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cpf" class="control-label"></label>
                <input asp-for="cpf" class="form-control" />
                <span asp-validation-for="cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rg" class="control-label"></label>
                <input asp-for="rg" class="form-control" />
                <span asp-validation-for="rg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="data_nasc" class="control-label"></label>
                <input type="date" asp-for="data_nasc" class="form-control" />
                <span asp-validation-for="data_nasc" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" onclick="alert('Professor cadstrado com sucesso')" />
                <a class="btn btn-secondary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AppSaresp_2024/Views/Professor/DetalhesProfessor.cshtml
@model AppSaresp_2024.Models.Professor

@{
    ViewData["Title"] = "DetalhesProfessor";
}

<h1>Detalhes do Professor</h1>
<br />
<div>
    <h4>Professor</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.IdProfessor) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.IdProfessor)  </dd>

        <dt class="col-sm-2">  @Html.DisplayNameFor(model => model.nome)  </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.nome) </dd>

        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.cpf) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.cpf)</dd>

        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.rg) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.rg)</dd>

        <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.telefone) </dt>
        <dd class="col-sm-10"> @Html.DisplayFor(model => model.telefone)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.data_nasc)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.data_nasc) </dd>
    </dl>
</div>
<br />
<div>
    @* <button type="button" class="btn btn-warning">
    @Html.ActionLink("Editar", "AtualizarProfessor", new { id = Model.IdProfessor })
    </button> *@
    <a class="btn btn-primary" asp-action="AtualizarProfessor">Editar</a>
    <a class="btn btn-secondary" asp-action="Index">Voltar</a>
    @* <button type="button" class="btn btn-secondary">
    @Html.ActionLink("Voltar", "Index")
    </button> *@
</div>

AppSaresp_2024/Views/Professor/Index.cshtml
@model IEnumerable<AppSaresp_2024.Models.Professor>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Professores</h1>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col"> @Html.DisplayNameFor(model => model.IdProfessor) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.nome) </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.cpf)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.rg)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.telefone)  </th>
                <th scope="col"> @Html.DisplayNameFor(model => model.data_nasc) </th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Professor professor in Model)
            {
                <tr>
                    <td>@professor.IdProfessor</td>
                    <td>@professor.nome</td>
                    <td>@professor.cpf</td>
                    <td>@professor.rg</td>
                    <td>@professor.telefone</td>
                    <td>@professor.data_nasc.ToString("dd/MM/yyyy")</td>
                    <td>
                        <button type="button" class="btn btn-warning botaoatualiza">
                            @Html.ActionLink("Editar", "AtualizarProfessor", new { id = professor.IdProfessor })
                        </button>

                        <button type="button" class="btn btn-secondary botaodetalhes">
                            @Html.ActionLink("Detalhes", "DetalhesProfessor", new { id = professor.IdProfessor })
                        </button>

                        <button type="button" class="btn btn-danger botaoexcluir">
                            @Html.ActionLink("Excluir", "ExcluirProfessor", new { id = professor.IdProfessor },
                                     new { onclick = "return confirm('Deseja realmente desativar?');" })
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<p><a class="btn btn-primary" asp-action="CadastrarProfessor" asp-controller="Professor">Cadastrar</a></p>

AppSaresp_2024/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppSaresp_2024</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppSaresp_2024.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppSaresp_2024</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Cadastro de Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Professor" asp-action="Index">Cadastro de Professores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppSaresp_2024 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>